name: Cypress run test with each pull request

on: [pull_request]
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5.5.1
